### ISSUE TITLE
Tracking Issue: Fixing provider DAGs

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#393]
## Problem

In #283, we ran an audit of our provider scripts and associated DAGs. This issue serves to track all of the issues that we found during that audit.

## Tasks

- [x] [Update API key for Brooklyn Museum DAG](https://github.com/WordPress/openverse-catalog/issues/385)
- [ ] [Update API key for Walters DAG](https://github.com/WordPress/openverse-catalog/issues/386)
- [ ] [Update API key for RawPixel DAG](https://github.com/WordPress/openverse-catalog/issues/387)
- [x] [Update API key for Smithsonian DAG](https://github.com/WordPress/openverse-catalog/issues/383)
- [x] [Update API key for NYPL DAG](https://github.com/WordPress/openverse-catalog/issues/384)
- [x] [Change Wikimedia Commons schedule interval to `@daily`](https://github.com/WordPress/openverse-catalog/issues/379)
- [x] [Handle duplicate keys in the TSV load_data task](https://github.com/WordPress/openverse-catalog/issues/388)
- [x] [Freesound pull_data task fails when getting audio file size](https://github.com/WordPress/openverse-catalog/issues/389)
- [x] [Museum Victoria DAG fails to pull data
](https://github.com/WordPress/openverse-catalog/issues/390)
- [x] [PhyloPic DAG detects no content even when data exists
](https://github.com/WordPress/openverse-catalog/issues/391)
- [x] [Finnish Museum pull_data freezes and times out](https://github.com/WordPress/openverse-catalog/issues/392)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
The Walter DAG is retired and we have the Rawpixel's API key, so we can close this.
