### ISSUE TITLE
Audit provider scripts to collect `filetype` and `filesize`

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-catalog#536]
## Current Situation

Currently, a lot of image provider scripts are not collecting the `filetype` and `filesize` information. This information can improve the frontend performance and make Openverse friendlier to providers by not requiring a `head` request for each image that lacks this information.

## Suggested Improvement

Image DAGs and what data they collect (the list is updated when the PRs are created or merged):

- [x] `smithsonian`: `filetype` ➖ ,`filesize` ➖ The API does not return `filetype`/`filesize`
- [x] `raw_pixel`: `filetype` ➖ ,`filesize` ➖ The API does not return `filetype`/`filesize`
- [x] `museum_victoria`: `filetype` ✅  ,`filesize` ✅  #600
- [x] `nypl`: `filetype` ✅  ,`filesize` ➖ #630 The API does not return `filesize`
- [x] `phylopic`: `filetype` ✅  ,`filesize` ➖ #547 The API does not return `filesize`
- [x] `science_museum`: `filetype` ✅  ,`filesize` ✅  #576
- [x] `smk`: `filetype` ✅  ,`filesize` ✅  #542
- [x] `cleveland_museum_of_art`: `filetype` ✅  ,`filesize` ✅  #537 
- [x] `metropolitan_museum_of_art`: `filetype` ✅  ,`filesize` ➖ #568 The API does not return `filesize`
- [x] `finnish_museums`: `filetype` ➖ ,`filesize` ➖ The API does not return `filetype`/`filesize`

Temporarily disabled DAGs that will need to be fixed later:
- `walters_art_museum`: `filetype` ➖ ,`filesize` ➖ Reason: no API key, #386
- `brooklyn_museum`: `filetype` ➖ ,`filesize` ➖ Reason: no API token, #385
- `europeana`: `filetype` ➖ ,`filesize` ➖ Reason: needs to be refactored for v2, #109 

Scripts that were already collecting `filetype` and `filesize` data:
- ✅  `flickr`: `filetype` ✅ ,`filesize`  ✅  - Uses image GET request
- ✅ `stocksnap`: `filetype` ✅ ,`filesize` ✅  Uses image GET request for filesize, and only has JPG
- ✅ `wikimedia_commons`: `filetype` ✅ ,`filesize` ✅  Has an ad-hoc function to compute filetype, needs to be updated to use the common util one
- ✅  `wordpress`: `filetype` ✅ ,`filesize` ✅ Has an ad-hoc function to compute filetype, needs to be updated to use the common util one

Then, separately, we'd need to write a script to backfill all existing records.
Finally, we would need a solution to collect the `filetype` and `filesize` for images whose provider scripts do not provide the data.

**Comment by obulat** [comment]
Auditing the provider scripts is done. Some scripts have been updated to collect available information.

For the providers that cannot be updated right away, I added comments to the follow up issues for related image dimension issues:
#646 https://github.com/WordPress/openverse-catalog/issues/646#issuecomment-1224293956
#647 https://github.com/WordPress/openverse-catalog/issues/647#issuecomment-1224300654
#648
